/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Elips: typeof import('./src/components/Elips/Elips.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    MyAwesomeIcon: typeof import('./src/components/MyAwesomeIcon/MyAwesomeIcon.vue')['default']
    MyButton: typeof import('./src/components/MyButton/MyButton.vue')['default']
    MyButtonIcon: typeof import('./src/components/MyButtonIcon/MyButtonIcon.vue')['default']
    MyElips: typeof import('./src/components/MyElips/MyElips.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader/MyHeader.vue')['default']
    MyProductCard: typeof import('./src/components/MyProductCard/MyProductCard.vue')['default']
    MyTitle: typeof import('./src/components/MyTitle/MyTitle.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
